# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12c04b162ba4d6a60b86beb73178e8bc94151aa718f012d1bf450d386b80baea91b76b68ef2ee42a472312a18d5c8613c4246d9c625190fd1b6e6ad35973df33

test:
  secret_key_base: 04d60dd0497bb0f61f47889e8b8cee547acab2396955454bc40d5b7bb7f345a8f059ead4f1e9cc02d52c382216ac461b0f9a8140350739d93a84a2d9f200a23d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
